Repository googleapis/java-shared-config, pull requests merged in 2020-10, with the labels that each got.

#195 chore: regenerate common templates
  .github/CODEOWNERS
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .github/workflows/formatting.yaml
  .github/workflows/samples.yaml
  .kokoro/build.sh
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  .kokoro/release/stage.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#198 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#199 docs: Latest for Cloud-RAD
  pom.xml
Labels: api: docs, cla: yes

#200 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: cla: yes, context: full

#202 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#203 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full
