Repository googleapis/java-shared-config, pull requests merged in 2020-06, with the labels that each got.

#146 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#147 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#150 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#151 feat: mark auto-value-annotations scope as provided
  pom.xml
Labels: automerge, cla: yes

#149 fix: lock the google-java-format version used by formatter plugin
  pom.xml
Labels: cla: yes

#159 fix: bump flatten plugin version to fix missing version in profile s…
  pom.xml
Labels: automerge, cla: yes

#163 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#171 feat: add ignore rule for javax annotations to handle error in java11
  pom.xml
Labels: cla: yes

#176 docs: change Devsite output path to /java/docs/reference
  pom.xml
Labels: cla: yes
