Repository googleapis/java-shared-config, pull requests merged in 2020-05, with the labels that each got.

#134 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#135 chore: update CONTRIBUTING.md to include code formatting
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#136 feat: add new configuration necessary to support auto-value
  pom.xml
Labels: cla: yes

#140 chore: Update the javadoc plugin to 3.2.0
  pom.xml
Labels: automerge, cla: yes
