Repository googleapis/java-shared-config, pull requests merged in 2021-02, with the labels that each got.

#216 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: cla: yes, context: full

#222 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: full

#223 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: cla: yes, context: full

#226 chore: update docfx config link
  pom.xml
Labels: cla: yes

#225 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#229 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/dependencies.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: full

#227 chore: updating docfx doclet version
  pom.xml
Labels: automerge, cla: yes

#231 ci: remove autorelease from this repo
  .github/workflows/auto-release.yaml
  synth.py
Labels: cla: yes

#230 feat: migrate releases to the new Google Sonatype endpoint
  pom.xml
Labels: cla: yes

#232 ci: clean up samples.yaml from this repo
  .github/workflows/samples.yaml
  synth.py
Labels: automerge, cla: yes, samples
