Repository googleapis/java-shared-config, pull requests merged in 2021-09, with the labels that each got.

#307 chore: use maven 3.8.1
  .github/workflows/downstream.yaml
Labels: cla: yes, automerge

#306 chore: use release-please to tag releases
  .github/release-please.yml
Labels: cla: yes, automerge

#304 chore: regenerate common templates
  .github/workflows/ci.yaml
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#312 fix: update java docfx doclet version
  pom.xml
Labels: cla: yes

#309 chore: remove linkage monitor required check
  .github/sync-repo-settings.yaml
Labels: cla: yes

#310 chore: re-generated to pick up changes from synthtool
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, automerge, context: full

#308 fix: specify animal-sniffer-maven-plugin version
  pom.xml
Labels: cla: yes

#315 fix: update java-docfx-doclet version
  pom.xml
Labels: cla: yes

#320 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes, automerge
