Repository googleapis/java-shared-config, pull requests merged in 2021-03, with the labels that each got.

#235 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#236 chore: remove v2 doc generation
  pom.xml
Labels: cla: yes

#237 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
