Repository googleapis/java-shared-config, pull requests merged in 2023-10, with the labels that each got.

#660 chore: publish native image docker images from java-shared-config
  .cloudbuild/cloudbuild-test.yaml
  .cloudbuild/cloudbuild.yaml
  .cloudbuild/google-cloud-sdk.repo
  .cloudbuild/graalvm22_3_jdk11.Dockerfile
  .cloudbuild/graalvm22_3_jdk11.yaml
  .cloudbuild/graalvm22_3_jdk17.Dockerfile
  .cloudbuild/graalvm22_3_jdk17.yaml
Labels: size: m

#669 deps: Update auto-value-annotation.version to v1.10.4
  .kokoro/java-storage-v2.9.3-expected-flattened-dependencies.txt
  pom.xml
Labels: size: xs

#662 test: add test for maven-javadoc-plugin version
  .github/sync-repo-settings.yaml
  .github/workflows/downstream-maven-plugins.yaml
  .kokoro/client-library-check-javadoc-with-doclet.sh
Labels: size: m

#671 Revert "build(deps): update dependency org.apache.maven.plugins:maven-javadoc-plugin to v3.6.0"
  pom.xml
Labels: automerge, size: xs

#674 chore: Renaming `auto-value-annotation.version` to `auto-value.version`
  pom.xml
Labels: size: xs

#676 docs: update README.md with AutoValue
  README.md
Labels: automerge, size: s

#664 chore: add kokoro job for verifying presence of docker image
  .kokoro/presubmit/graalvm-docker.cfg
  .kokoro/verify-docker-images.sh
Labels: size: s

#677 ci: mark javadoc-with-doclet as required
  .github/sync-repo-settings.yaml
Labels: size: xs

#681 chore: Update downstream-dependencies.yaml with java-bigquerystorage
  .github/workflows/downstream-dependencies.yaml
Labels: size: xs

#683 feat: add graal-sdk dependency management to java-shared-config
  pom.xml
Labels: size: xs

#688 chore: add java-shared-config to safe.directory and mark docker validation check as required
  .github/sync-repo-settings.yaml
  .kokoro/verify-docker-images.sh
Labels: size: xs

#689 chore: avoid masking errors in docker validation script
  .kokoro/verify-docker-images.sh
Labels: size: xs

#690 chore: update docker image tag to 1.6.0
  .cloudbuild/cloudbuild-test.yaml
  .cloudbuild/cloudbuild.yaml
Labels: size: xs

#703 deps: update graal-sdk to 22.3.3
  .cloudbuild/cloudbuild-test.yaml
  .cloudbuild/cloudbuild.yaml
  .cloudbuild/graalvm22_3_jdk11.Dockerfile
  .cloudbuild/graalvm22_3_jdk11.yaml
  .cloudbuild/graalvm22_3_jdk17.Dockerfile
  .cloudbuild/graalvm22_3_jdk17.yaml
  pom.xml
Labels: size: s

#704 chore: update downstream tests to graalvm 22.3.3
  .kokoro/presubmit/graalvm-native-17.cfg
  .kokoro/presubmit/graalvm-native.cfg
Labels: size: xs
