Repository googleapis/java-shared-config, pull requests merged in 2024-02, with the labels that each got.

#738 chore: update java-shared-config version based on current version
  .cloudbuild/cloudbuild.yaml
Labels: size: xs

#744 fix: update docFX config
  java-shared-config/pom.xml
Labels: size: s

#754 chore: use sdk-platform-java-config for java-bigquery
  .kokoro/client-library-check.sh
Labels: size: xs

#755 chore: update doclet test to use updated `sdk-platform-java-config` artifact
  .github/workflows/downstream-maven-plugins.yaml
  .kokoro/client-library-check-doclet.sh
  .kokoro/client-library-check-javadoc-with-doclet.sh
Labels: size: m

#749 chore: remove obsolete kokoro release configs
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/bump_snapshot.sh
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.cfg
  .kokoro/release/drop.sh
  .kokoro/release/promote.cfg
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  owlbot.py
Labels: size: xl

#758 chore: remove Kokoro - Docker Image Validation check
  .github/sync-repo-settings.yaml
Labels: automerge, size: xs

#767 Revert "build(deps): update dependency org.codehaus.mojo:flatten-mave…
  java-shared-config/pom.xml
Labels: size: xs
