Repository googleapis/java-shared-config, pull requests merged in 2024-08, with the labels that each got.

#881 fix: address terraform installation failure by updating hashicorp baseurl
  .cloudbuild/hashicorp.repo
Labels: size: xs

#877 feat: update test image to ol9
  .cloudbuild/docker-ce.repo
  .cloudbuild/graalvm-a.Dockerfile
Labels: size: s

#886 deps: update com.google.auto.value:auto-value-annotations to 1.11.0
  .kokoro/java-storage-v2.9.3-expected-flattened-dependencies.txt
  java-shared-config/pom.xml
Labels: size: xs

#895 chore: remove owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  codecov.yaml
  owlbot.py
  synth.metadata
Labels: size: m
