Repository googleapis/java-shared-config, pull requests merged in 2025-01, with the labels that each got.

#965 chore: temporarily disable auto value dependency updates until after LTS release
  renovate.json
Labels: size: xs

#967 chore: update GraalVM image B to GraalVM for JDK 23
  .cloudbuild/graalvm-b.Dockerfile
  .cloudbuild/graalvm-b.yaml
Labels: size: s

#974 chore: remove artifactregistry-maven-wagon
  native-image-shared-config/pom.xml
Labels: size: s

#975 fix: animal-sniffer-maven-plugin to a profile
  java-shared-config/pom.xml
Labels: size: m
